# Generated by Django 4.1 on 2023-11-28 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockTracker', '0002_rename_toy_id_toy_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toy',
            name='size',
        ),
    ]
