# Generated by Django 4.1 on 2023-11-30 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockTracker', '0003_remove_toy_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='toy',
            name='name',
            field=models.CharField(default='NOT_SET', max_length=200),
            preserve_default=False,
        ),
    ]
